version: "3.7"
services:
  tensorflow:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    container_name: 'tf_gpu'
    runtime: nvidia
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:6006:6006"
    volumes:
      - ./Notebooks:/tf/Notebooks
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
